name 'example42-icinga'
version '2.0.10'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-icinga'
summary 'Puppet module for icinga'
description 'This module installs and manages icinga. Check README.rdoc for details. Puppi is required for some common functions: you can install them without using the whole module. Monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
dependency 'example42/nrpe', '>=2.0.0'
dependency 'example42/apt', '>=0.1.9'
dependency 'example42/mysql', '>=2.0.0'
dependency 'rivieraal/concat', '>=0.0.1'
